#!/usr/bin/env bash

# preview script
# github.com/rafi/.config

FILE="${1}"
HEIGHT="${2}"

[ -L "${FILE}" ] && FILE="$(readlink "${FILE}")"

# show file title
# echo -e "\e[33m# \e[34m$(basename "${FILE}")\e[0m"

# preview for archives and json/xml
case "${FILE}" in
	*.tar*) tar tf "${FILE}"; exit 0;;
	*.zip) unzip -l "${FILE}"; exit 0;;
	*.rar) unrar l "${FILE}"; exit 0;;
	*.7z) 7z l "${FILE}"; exit 0;;
	*.gz|*.bzip|*.bzip2|*.bp|*.bz2) als "${FILE}"; exit 0;;
	*.json) jq -C . "${FILE}" && exit 0;;
	*.md) glow -s dark "${FILE}" && exit 0;;
	*.xml) xmlstarlet fo "${FILE}" && exit 0;;
	*.plist) plutil -p "${FILE}"; exit 0;;
esac

# use the right tool for the mimetype label
case "$(file -b --mime-type "${FILE}")" in

	# multimedia metadata information with mediainfo/id3ted/exiftool/id3info
	video/*|audio/*)
		mediainfo "${FILE}" | sed 's/ *:/:/g' || \
			id3ted -L "${FILE}" || \
			exiftool "${FILE}" || \
			id3info "${FILE}"
		exit 0;;

	# opendocument with pandoc/odt2txt
	application/vnd.oasis.opendocument*)
		pandoc "${FILE}" --to=markdown || odt2txt "${FILE}"
		exit 0;;

	# pdf first sheet screenshot with pdftoppm and chafa or pdftotext
	application/pdf)
		if hash pdftoppm 2>/dev/null && hash chafa 2>/dev/null; then
			w3m --fill=space -c 256 -s 80x"${HEIGHT}" <(pdftoppm -f 1 -l 1 \
				-scale-to-x 1920 \
				-scale-to-y -1 \
				-singlefile \
				-jpeg -tiffcompression jpeg \
				-- "${FILE}")
		else
			pdftotext -l 10 -nopgbrk -q -- "${FILE}" -
		fi
		exit 0;;

	# all other types use bat/pygmentize/highlight/cat
	*)
		bat "${FILE}" || \
		exit 0
		;;
esac

# vim: set ts=2 sw=2 tw=80 noet :
