#============================================================
# P10K CONFIGURATION FILE
# OWNERSHIP: USER
# PABLO AGUIRRE NÚÑEZ
#============================================================

#------------------------------------------------------------
# BEGINNING OF P10K CONFIGURATION FILE
#------------------------------------------------------------
#============================================================
# General Configuration
#============================================================
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
POWERLEVEL9K_MODE="powerline"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
# Disable default p10k icons
POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=
POWERLEVEL9K_TRANSIENT_PROMPT=always
#============================================================
# Separators
#============================================================
# Field separators
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0B1'
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0B3'
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B0'
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B2'
POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=
POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=
POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''

# Newline separators
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{8}\u250C\u2500%F{8}"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{8}\u2514\u2500%F{8} "

# Left and right prompt connector
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR='─'
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND='clear'
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=15

#============================================================
# Prompt elements
#============================================================
# Elements
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir dir_writable_joined)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time vcs background_jobs_joined vi_mode)

# Context (Bold)
POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%B%n'
POWERLEVEL9K_CONTEXT_TEMPLATE='%B%n'

# Command execution time
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=1
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='clear'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=1
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_VISUAL_IDENTIFIER_EXPANSION=' '

# Icons
POWERLEVEL9K_DIR_SHOW_WRITABLE=true
POWERLEVEL9K_DIR_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION='∅'
POWERLEVEL9K_VCS_UNTRACKED_ICON=''

# Status
POWERLEVEL9K_STATUS_OK=true
POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION=' '

#============================================================
# Colorscheme
#============================================================
# VCS
POWERLEVEL9K_VCS_CLEAN_BACKGROUND=8
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=12
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=7
POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=1
POWERLEVEL9K_VCS_LOADING_BACKGROUND=3

POWERLEVEL9K_VCS_CLEAN_FOREGROUND=0
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=0
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=0
POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=0
POWERLEVEL9K_VCS_LOADING_FOREGROUND=0

# Last command status
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=8
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=1

# Context
POWERLEVEL9K_CONTEXT_SUDO=8
POWERLEVEL9K_CONTEXT_SUDO_BACKGROUND="clear"
POWERLEVEL9K_CONTEXT_FOREGROUND=1
POWERLEVEL9K_CONTEXT_BACKGROUND='clear'

# Directories
POWERLEVEL9K_DIR_HOME_BACKGROUND="clear"
POWERLEVEL9K_DIR_HOME_FOREGROUND=1

POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='clear'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND=7

POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="clear"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND=1

POWERLEVEL9K_DIR_BACKGROUND='clear'
POWERLEVEL9K_DIR_FOREGROUND=12

POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="clear"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND=1

POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="clear"
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND=1

POWERLEVEL9K_STATUS_OK_BACKGROUND="clear"
POWERLEVEL9K_STATUS_OK_FOREGROUND=1
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="clear"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND=1
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='clear'
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='green'

#============================================================
# vi mode
#============================================================
# Foreground color.
POWERLEVEL9K_VI_MODE_FOREGROUND=0
# Text and color for normal (a.k.a. command) vi mode.
POWERLEVEL9K_VI_COMMAND_MODE_STRING=NO
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND=1
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='clear'

# Text and color for visual vi mode.
POWERLEVEL9K_VI_VISUAL_MODE_STRING=VI
POWERLEVEL9K_VI_MODE_VISUAL_FOREGROUND=11
POWERLEVEL9K_VI_MODE_VISUAL_BACKGROUND='clear'

# Text and color for overtype (a.k.a. overwrite and replace) vi mode.
POWERLEVEL9K_VI_OVERWRITE_MODE_STRING=OV
POWERLEVEL9K_VI_MODE_OVERWRITE_FOREGROUND=2
POWERLEVEL9K_VI_MODE_OVERWRITE_BACKGROUND='clear'

# Text and color for insert vi mode.
POWERLEVEL9K_VI_INSERT_MODE_STRING=IN
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND=12
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='clear'

# Set vim filetype
# vim: set ft=zsh:

#------------------------------------------------------------
# END OF P10K CONFIGURATION FILE
#------------------------------------------------------------
